### ISSUE TITLE
Times Lab Syntax issue

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/looping-times#9]
this works: 
def using_times
	7.times do 
	  puts 'Wingardium Leviosa'
	end
end

this does not, ( ass expressed within the given examples)

7.times do 
  puts "I am doing the dishes left by my former friends."
end
(expecting another "end" statement to close the method)

**Comment by lizbur10** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
